[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Haymondm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.2.12"
rand = "^0.8.3"
